### ISSUE TITLE
cannot import name 'scrape_video'

### ISSUE THREAD

**Issue by sonaldynho** [morpheusthewhite/jwscraper#8]
cannot import name 'scrape_video'

**Comment by morpheusthewhite** [comment]
What lines produce that error?

**Comment by sonaldynho** [comment]
[Image][Image]
Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: morpheusthewhite <notifications@github.com>
Enviado: Sunday, July 14, 2019 3:05:53 AM
Para: morpheusthewhite/jwscraper
Cc: sonaldynho; Author
Assunto: Re: [morpheusthewhite/jwscraper] cannot import name 'scrape_video' (#8)


What lines produce that error?

**Comment by morpheusthewhite** [comment]
I see nothing

**Comment by sonaldynho** [comment]
code
from jwscraper import scrape_video, scrape_save_video
scrape_video(url, bypass_cloudflare=True)
scrape_save_video(url, filename=None, bypass_cloudflare=True)

**Comment by sonaldynho** [comment]
erro
Traceback (most recent call last):
  File "C:\Users\danfl\Documents\bingo,py.py", line 15, in <module>
    from jwscraper import scrape_video, scrape_save_video
ImportError: cannot import name 'scrape_video'

**Comment by morpheusthewhite** [comment]
Did you follow instructions to install the package?

**Comment by sonaldynho** [comment]
I m using windows.
I just downloaded de zip and unzip on my python 36 folder

**Comment by morpheusthewhite** [comment]
You need to launch pip with the command in the README to work
